lib/graphql/schema.ts, lib/graphql/types/taxonomy.ts, test/integration/__fixtures__/taxonomy.ts, test/integration/skills.spec.ts, test/integration/taxonomy.spec.ts
https://trello.com/c/4q1trAjr/19-implement-work-experience-using-jobtech-taxonomy
=> feat: add support for all taxonomy types

.github/PULL_REQUEST_TEMPLATE.md
Added a PR template for improved conformity in PRs
=> feat: add pr template

lib/adapters/__tests__/mydata.spec.ts, lib/adapters/__tests__/taxonomy.spec.ts, lib/adapters/taxonomy.ts, lib/graphql/__tests__/schema.spec.ts, lib/graphql/resolvers/mutations/__tests__/removeEducation.spec.ts, lib/graphql/resolvers/mutations/__tests__/removeExperience.spec.ts, lib/graphql/resolvers/mutations/__tests__/removeLanguage.spec.ts, lib/graphql/resolvers/mutations/__tests__/removeSkill.spec.ts, lib/graphql/resolvers/mutations/removeLanguage.ts, lib/graphql/resolvers/queries/__tests__/profile.spec.ts, lib/graphql/resolvers/queries/__tests__/taxonomy.spec.ts
**Ticket:** [#33](https://trello.com/c/78Xt6KTg/33-add-tests-for-all-code-100percentcoverage)
**Intent:**
Add test coverage
npm test
=> test: 100% coverage

graphql.schema.json, lib/__generated__/myskills.d.ts, lib/adapters/__tests__/mydata.spec.ts, lib/adapters/mydata.ts, lib/graphql/__mocks__/apolloServerContext.ts, lib/graphql/resolvers/mutations/__tests__/addEducation.spec.ts, lib/graphql/resolvers/mutations/__tests__/addExperience.spec.ts, lib/graphql/resolvers/mutations/__tests__/addLanguage.spec.ts, lib/graphql/resolvers/mutations/__tests__/addSkill.spec.ts, lib/graphql/resolvers/mutations/addEducation.ts, lib/graphql/resolvers/mutations/addExperience.ts, lib/graphql/resolvers/mutations/addLanguage.ts, lib/graphql/resolvers/mutations/addSkill.ts, lib/graphql/types/index.ts, lib/server.ts, lib/typings/context.d.ts, test/integration/educations.spec.ts, test/integration/experiences.spec.ts, test/integration/languages.spec.ts, test/integration/skills.spec.ts
~BASED ON https://github.com/JobtechSwe/myskills-api/pull/15, merge that one first!~ **DONE**
**Ticket:** [#43](https://trello.com/c/zBNok9Uv/43-only-return-added-object)
**Intent:**
Only return the added object, not the complete list
=> feat: only return added objects

infrastructure/openshift/README.md, infrastructure/openshift/setup/redis-test-pvc.yml, infrastructure/openshift/shared/api-BuildConfig.yml, infrastructure/openshift/shared/api-ImageStream.yml, infrastructure/openshift/test/api-DeploymentConfig.yml, infrastructure/openshift/test/api-Route.yml, infrastructure/openshift/test/api-Service.yml, infrastructure/openshift/test/redis-DeploymentConfig.yml, infrastructure/openshift/test/redis-Service.yml, infrastructure/travis/README.md
**Ticket:** [#](https://trello.com/c/xmHRToq7/38-add-travis-ci)
**Intent:**
- added a test environment  in Openshift
- updated README for Openshift and Travis
=> ci: 🎡 added test api in openshift and updated READMEs

infrastructure/travis/build.sh, infrastructure/travis/deploy.sh, infrastructure/travis/install-openshift.sh
**Ticket:** [#38](https://trello.com/c/xmHRToq7/38-add-travis-ci)
**Intent:**
Before the scripts that travis runs did not return error codes. Now throws if something failed in any of the scripts.
=> chore: throw error from failed travis scripts

.github/PULL_REQUEST_TEMPLATE.md
**Intent:**
Now that we've added travis that automatically runs the tests, it's just a chore to tick those boxes
=> chore: remove redundancy in pr template

README.md
**Ticket:** [#46](https://trello.com/c/JZnUpx03/46-document-myskills-schema)
Add schema to documentation
=> docs: add schema to docs

LICENSE
**Ticket:** [#34](https://trello.com/c/8aUoBHWu/34-add-license-to-myskills-repo)
=> chore: use apache 2 license

package-lock.json, package.json
**Ticket:** None
**Intent:** Update of MyData client package
**How to test :** Nope
=> chore(deps): bumped mydata client version

.travis.yml, README.md
**Ticket:** [#31](https://trello.com/c/wHPV3uBl/31-add-badges-for-test-coverage-in-github)
**Intent:**
Add code test coverage badge to readme
=> chore: code coverage

graphql.schema.json, lib/__generated__/myskills.d.ts, lib/adapters/__tests__/taxonomy.spec.ts, lib/adapters/taxonomy.ts, lib/graphql/resolvers/queries/__tests__/taxonomy.spec.ts, lib/graphql/resolvers/queries/taxonomy.ts, lib/graphql/types/taxonomy.ts, package-lock.json, package.json
**Ticket:** [#57](https://trello.com/c/PWEOzeoV/57-add-support-for-taxonomy-queries-to-take-a-parentid)
**Intent:**
To query taxonomy for related to parent id
=> Feat: parent id search

.travis.yml
**Ticket:** [#66](https://trello.com/c/f2lhkZFg/66-change-travis-flow)
**Intent:**
Create tag release in github before trying to build and deploy
=> chore(travis): tag before build and deploy

docker-compose.yml, lib/adapters/__tests__/mydata.spec.ts, lib/config.ts, lib/services/__tests__/__snapshots__/consents.spec.ts.snap, lib/services/__tests__/consents.spec.ts
**Ticket:** [#](TRELLOURL)
**Intent:**
Fixes some minor things that were not as expected (for me), and makes it easier to develop inside docker-land.
=> chore: fix docker compose

.travis.yml
**Ticket:** [#74](https://trello.com/c/b27SCdci/74-combine-coverage-with-test-stages)
Combine test and coverage steps in travis. Master build time is currently reduced by approx. 1 min
=> chore(travis): combine test and coverage script

lib/server.ts, test/integration/integrationUtils.ts
**Intent:** Adds some error logs that helps getting to the root of the cause.
=> chore: add error logging

README.md, graphql.schema.json, lib/__generated__/myskills.d.ts, lib/graphql/resolvers/mutations/__tests__/addEducation.spec.ts, lib/graphql/resolvers/mutations/__tests__/addExperience.spec.ts, lib/graphql/resolvers/mutations/__tests__/addSkill.spec.ts, lib/graphql/types/education.ts, lib/graphql/types/experience.ts, test/integration/educations.spec.ts, test/integration/experiences.spec.ts
**Ticket:** [#100](https://trello.com/c/CGl64nbh/100-inconsistence-between-graphql-queries)
**Intent:** Fix inconsitency issues in graphql interface
=> fix: use term instead of name in gql interface

.travis.yml
**Ticket:** [#85](https://trello.com/c/SOLkg2kx/85-move-encrypted-travis-variables-from-being-in-the-config-to-having-them-inside-travis-web-ui)
**Intent:**
Move secrets from travis cli to travis web ui
Build
=> chore: move secrets to travis web UI instead

package.json
Add apache 2 license to package.json
=> chore(package): add correct license

lib/graphql/resolvers/mutations/saveCV.ts
=> chore: clean since mydata fixed bug with simultaneously writes

docker-compose.yml, lib/graphql/resolvers/mutations/login.ts, lib/graphql/resolvers/queries/__tests__/taxonomy.spec.ts, lib/graphql/resolvers/queries/taxonomy.ts, test/integration/__fixtures__/taxonomy.ts
**Intent:** Docker is not able to fetch config from the current config path. This simplifies it and makes it work.
=> fix: path to config.js malformed

lib/graphql/resolvers/mutations/__tests__/saveCV.spec.ts
=> test: fix typescript warnings

graphql.schema.json, lib/__generated__/myskills.d.ts, lib/graphql/resolvers/mutations/__tests__/saveCV.spec.ts, lib/graphql/resolvers/mutations/saveCV.ts, lib/graphql/resolvers/mutations/uploadImage.ts, lib/graphql/types/cv.ts, lib/utils/image.ts, test/features/SaveCV.feature, test/features/gql/index.ts, test/features/steps/save-cv.steps.ts
**Ticket:** [#158](https://trello.com/c/YOjEoWZk/158-skicka-med-bild-i-spara-cv)
**Intent:**
Allow image to be sent into save-cv
=> feat: add image to savecv

lib/utils/image.ts
=> fix(image): parse base64 image

graphql.schema.json, lib/__generated__/myskills.d.ts, lib/graphql/resolvers/mutations/saveCV.ts, lib/graphql/types/cv.ts
**Ticket:** [#166](https://trello.com/c/7K3bGtDn/166-skicka-med-kontaktuppgifter-i-spara-cv)
**Intent:**
save cv mutation should take profile info
=> feat: save cv profile

.travis.yml
**Ticket:** [#170](https://trello.com/c/5MRHMDG2/170-fixa-release-av-r%C3%A4tt-image)
=> chore: await docker images being pushed to hub

graphql.schema.json, lib/__generated__/myskills.d.ts, lib/graphql/types/education.ts
**Ticket:** [#182](https://trello.com/c/rjSm3crk/182-add-degree-to-education-in-api)
**Intent:**
=> feat: add degree as optional to education
